// Fetch all categories from the database
import supabase from "./configuration.js";

const fetchCategories = async () => {
  const { data, error } = await supabase.from('categories').select();
  return { data, error };
}

// Fetch tag Groups
const fetchTagGroups = async () => {
  const { data, error } = await supabase.from('tag_groups').select();
  return { data, error };
}

// Fetch all tags from the database
const fetchTags = async () => {
  const {data, error} = await supabase.from('tags').select(`name, tag_groups (name)`);
  return { data, error };
}

// Fetch links between categories and tag_groups generated by LLM
const fetchLLMGeneratedLinks = async () => {
  const { data, error } = await supabase.from('llm_generated_links').select(`categories (name), tag_groups (name)`);
  return { data, error };
}

export {
  fetchCategories,
  fetchTagGroups,
  fetchTags,
  fetchLLMGeneratedLinks,
};