// Fetch all categories from the database
import supabase from "./configuration.js";

const fetchCategories = async () => {
  const { data, error } = await supabase.from('categories').select();
  return { data, error };
}

// Fetch tag Groups
const fetchTagGroups = async () => {
  const { data, error } = await supabase.from('tag_groups').select();
  return { data, error };
}

// Fetch all tags from the database
const fetchTags = async () => {
  const {data, error} = await supabase.from('tags').select(`name, tag_groups (name)`);
  return { data, error };
}

// Fetch links between categories and tag_groups generated by LLM
const fetchLLMGeneratedLinks = async () => {
  const { data, error } = await supabase.from('llm_generated_links').select(`categories (name), tag_groups (name)`);
  return { data, error };
}

// Fetch experiences based on a tag name
const fetchExperienceHeadlinesFromTag = async (tag) => {
  const { data, error } = await supabase.rpc('get_experience_headlines_from_tag', {
    tag_name: tag,
  }).select();
  return { data, error };
}

// Search experiences based on a search term
const searchExperiences = async (searchTerm) => {
  const { data, error } = await supabase.rpc('search_experiences', {
    search_value: searchTerm,
  }).select();
  return { data, error };
}

export {
  fetchCategories,
  fetchTagGroups,
  fetchTags,
  fetchLLMGeneratedLinks,
  fetchExperienceHeadlinesFromTag,
  searchExperiences,
};